[project]
name = "axe"
version = "0.1.0"
description = "An EVM CLI Tool built in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.0",
    "rich>=14.0.0",
    "typer>=0.16.0",
    "web3>=7.12.0",
]
